version: '3.8'

services:
  vibe-coding-service:
    image: ghcr.io/several-magicians/metaid_vibe_coding_service:v1.1
    container_name: vibe-coding-service
    platform: linux/amd64
    ports:
      - "7389:3000"
    volumes:
      - ./projects:/app/projects
      - ./logs:/app/logs
    restart: always

